Expect strings in calls to lookup("env", "CI")
GitHub Actions is returning strings instead of booleans for this
environment variable when using Ubuntu 24.04 [1]. We were getting the
following error:

```
Error: : Task failed: Conditional result (True) was derived from value
of type 'str' at "<environment variable 'CI'>". Conditionals must have a
boolean result.

Task failed.  Origin:
/home/runner/work/installer/installer/roles/letsencrypt/tasks/main.yml:33:7
```

[1] See discussion 3217 in https://github.com/actions/runner