Add support for Debian Trixie
We're still supporting Debian Bullseye because it'll be supported by
Debian until August 2026.

Note we need to use the `callback_result_format=yaml` option; we were
getting an error on github actions with Debian Trixie:

```
[DEPRECATION WARNING]: community.general.yaml has been deprecated. The
plugin has been superseded by the the option `result_format=yaml` in
callback plugin ansible.builtin.default from ansible-core 2.13 onwards.
This feature will be removed from collection 'community.general' version
13.0.0.

Error: : Unexpected Exception, this is probably a bug: module
'ansible._internal._yaml._dumper' has no attribute 'SafeRepresenter'
```

The `result_format` option (which must be prefixed with `callback_` when
used in the `ansible.cfg` file [1]) was introduced in ansible-core 2.13,
released in May 2022. So we're using it instead and updating the
requirements.

The package `policykit-1` was been replaced by `polkitd` and `pkexec`.
Ubuntu 22.04, Ubuntu 24.04 and Debian Bookworm support both cases.
However, Debian Bullseye only supports `policykit-1` while Debian Trixie
only supports the `polkitd` and `pkexec` combo. So we're adding a
condition.

We also need to explicitly install `gpg` since the Debian Trixie image
on github actions doesn't include it by default, and we need it in order
to install RVM.

Finally, we're using an empty string for `rvm1_ruby_install_flags`,
since the default empty value now results in an error due to a `None`
argument being added to the command:

```
- name: Install rubies
  ^ column 3

failed: [localhost] (item=ruby-3.3.10) =>
    ansible_loop_var: item
    changed: true
    cmd:
    - ~/.rvm/bin/rvm
    - install
    - ruby-3.3.10
    - None
    delta: '0:00:00.337518'
    end: '2025-11-04 18:30:55.085785'
    item: ruby-3.3.10
    msg: non-zero return code
    rc: 1
    start: '2025-11-04 18:30:54.748267'
    stderr: 'Unrecognized command line argument: None'
    stderr_lines: <omitted>
    stdout: Run `rvm help` to see usage information
    stdout_lines: <omitted>
```

[1] https://docs.ansible.com/ansible/latest/collections/ansible/builtin/default_callback.html#parameter-result_format